const mockFindByIngredient = () => [{
  id: 37341,
  title: 'Stir-fried Soybean Sprouts',
  image: 'https://spoonacular.com/recipeImages/37341-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 1,
  missedIngredientCount: 2,
  missedIngredients: [
    {
      id: 11215,
      amount: 4.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'cloves garlic',
      original: '4 x cloves garlic',
      originalString: '4 x cloves garlic',
      originalName: 'x cloves garlic',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.jpg',
    },
    {
      id: 11291,
      amount: 3.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'green onions',
      original: '3 x green onions',
      originalString: '3 x green onions',
      originalName: 'x green onions',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
    },
  ],
  usedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'lb',
      unitLong: 'pound',
      unitShort: 'lb',
      aisle: 'Produce',
      name: 'sprouts',
      original: '1 lb Soybean Sprouts',
      originalString: '1 lb Soybean Sprouts',
      originalName: 'Soybean Sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  unusedIngredients: [],
  likes: 9,
},
{
  id: 19021,
  title: 'Tomatoes, Mixed Bean Sprouts And Mixed Leaves',
  image: 'https://spoonacular.com/recipeImages/19021-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 1,
  missedIngredientCount: 2,
  missedIngredients: [
    {
      id: 2004,
      amount: 1.0,
      unit: 'leaves',
      unitLong: 'leave',
      unitShort: 'leaf',
      aisle: 'Produce;Spices and Seasonings',
      name: 'bay leaves',
      original: 'Mixed leaves (Radicchio, Lettuce and Curly)',
      originalString: 'Mixed leaves (Radicchio, Lettuce and Curly)',
      originalName: 'Mixed (Radicchio, Lettuce and Curly)',
      metaInformation: [
        'mixed',
        '(Radicchio, Lettuce and Curly)',
      ],
      meta: [
        'mixed',
        '(Radicchio, Lettuce and Curly)',
      ],
      extendedName: 'mixed bay leaves',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bay-leaves.jpg',
    },
    {
      id: 11696,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'yellow tomatoes',
      original: 'Yellow and Red tomatoes',
      originalString: 'Yellow and Red tomatoes',
      originalName: 'Yellow and Red tomatoes',
      metaInformation: [
        'red',
        'yellow',
      ],
      meta: [
        'red',
        'yellow',
      ],
      extendedName: 'red yellow tomatoes',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato-yellow.png',
    },
  ],
  usedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'Sprouts beans (Chickpeas, Lentils and other beans)',
      originalString: 'Sprouts beans (Chickpeas, Lentils and other beans)',
      originalName: 'Sprouts beans (Chickpeas, Lentils and other beans)',
      metaInformation: [
        '(Chickpeas, Lentils and other beans)',
      ],
      meta: [
        '(Chickpeas, Lentils and other beans)',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  unusedIngredients: [],
  likes: 9,
},
{
  id: 22721,
  title: 'Cucumber Cups',
  image: 'https://spoonacular.com/recipeImages/22721-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 1,
  missedIngredientCount: 2,
  missedIngredients: [
    {
      id: 11206,
      amount: 2.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'cucumbers',
      original: '2 seedless cucumbers (each 9 1/2 inches long), washed',
      originalString: '2 seedless cucumbers (each 9 1/2 inches long), washed',
      originalName: 'seedless cucumbers (each 9 1/2 inches long), washed',
      metaInformation: [
        'seedless',
        'washed',
      ],
      meta: [
        'seedless',
        'washed',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/cucumber.jpg',
    },
    {
      id: 1016,
      amount: 0.5,
      unit: 'cup',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Cheese',
      name: 'low fat cottage cheese',
      original: '1/2 cup low-fat cottage cheese',
      originalString: '1/2 cup low-fat cottage cheese',
      originalName: 'low-fat cottage cheese',
      metaInformation: [
        'low-fat',
      ],
      meta: [
        'low-fat',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/cottage-cheese.jpg',
    },
  ],
  usedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'Clove',
      unitLong: 'Clove',
      unitShort: 'Clove',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'Clover sprouts',
      originalString: 'Clover sprouts',
      originalName: 'r sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  unusedIngredients: [],
  likes: 2,
},
{
  id: 489315,
  title: 'Slow Cooker Sesame Beef Noodle Bowls',
  image: 'https://spoonacular.com/recipeImages/489315-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11043,
      amount: 4.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Produce',
      name: 'bean sprouts',
      original: 'bean sprouts',
      originalString: 'bean sprouts',
      originalName: 'bean sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
    {
      id: 11291,
      amount: 4.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Produce',
      name: 'green onions',
      original: 'green onions',
      originalString: 'green onions',
      originalName: 'green onions',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
    },
    {
      id: 20133,
      amount: 4.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Pasta and Rice;Gluten Free;Ethnic Foods',
      name: 'rice noodles',
      original: 'Flat rice noodles (pad thai noodles)',
      originalString: 'Flat rice noodles (pad thai noodles)',
      originalName: 'Flat rice noodles (pad thai noodles)',
      metaInformation: [
        '(pad thai noodles)',
      ],
      meta: [
        '(pad thai noodles)',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/dried-rice-noodles.jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 800,
},
{
  id: 660115,
  title: 'Simple Mung Bean Sprouts',
  image: 'https://spoonacular.com/recipeImages/660115-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11043,
      amount: 2.0,
      unit: 'cups',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Produce',
      name: 'mung bean sprouts',
      original: '2 cups mung bean sprouts, rinsed',
      originalString: '2 cups mung bean sprouts, rinsed',
      originalName: 'mung bean sprouts, rinsed',
      metaInformation: [
        'rinsed',
      ],
      meta: [
        'rinsed',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
    {
      id: 19912,
      amount: 1.0,
      unit: 'tablespoon',
      unitLong: 'tablespoon',
      unitShort: 'Tbsp',
      aisle: 'Ethnic Foods;Health Foods',
      name: 'agave nectar',
      original: '1 tablespoon agave nectar (or preferred sweetener)',
      originalString: '1 tablespoon agave nectar (or preferred sweetener)',
      originalName: 'agave nectar (or preferred sweetener)',
      metaInformation: [
        '(or preferred sweetener)',
      ],
      meta: [
        '(or preferred sweetener)',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/agave.png',
    },
    {
      id: 1022020,
      amount: 0.5,
      unit: 'teaspoon',
      unitLong: 'teaspoons',
      unitShort: 'tsp',
      aisle: 'Spices and Seasonings',
      name: 'garlic powder',
      original: '1/2 teaspoon garlic powder',
      originalString: '1/2 teaspoon garlic powder',
      originalName: 'garlic powder',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic-powder.png',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 1,
},
{
  id: 113044,
  title: 'Seasoned Mung Bean Sprouts--Sukju Namul Muchim',
  image: 'https://spoonacular.com/recipeImages/113044-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11215,
      amount: 2.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'garlic cloves',
      original: '2 garlic cloves, minced',
      originalString: '2 garlic cloves, minced',
      originalName: 'garlic cloves, minced',
      metaInformation: [
        'minced',
      ],
      meta: [
        'minced',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.jpg',
    },
    {
      id: 11291,
      amount: 2.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'green onions',
      original: '2 green onions',
      originalString: '2 green onions',
      originalName: 'green onions',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
    },
    {
      id: 11043,
      amount: 8.0,
      unit: 'ounces',
      unitLong: 'ounces',
      unitShort: 'oz',
      aisle: 'Produce',
      name: 'mung bean sprouts',
      original: '8 ounces fresh mung bean sprouts',
      originalString: '8 ounces fresh mung bean sprouts',
      originalName: 'fresh mung bean sprouts',
      metaInformation: [
        'fresh',
      ],
      meta: [
        'fresh',
      ],
      extendedName: 'fresh mung bean sprouts',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 1,
},
{
  id: 34410,
  title: 'Mung Bean Sprout Salad',
  image: 'https://spoonacular.com/recipeImages/34410-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11043,
      amount: 1.0,
      unit: 'pound',
      unitLong: 'pound',
      unitShort: 'lb',
      aisle: 'Produce',
      name: 'mung bean sprouts',
      original: '1 pound rinsed mung bean sprouts',
      originalString: '1 pound rinsed mung bean sprouts',
      originalName: 'rinsed mung bean sprouts',
      metaInformation: [
        'rinsed',
      ],
      meta: [
        'rinsed',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
    {
      id: 12023,
      amount: 1.0,
      unit: 'tablespoon',
      unitLong: 'tablespoon',
      unitShort: 'Tbsp',
      aisle: 'Ethnic Foods;Spices and Seasonings',
      name: 'sesame seeds',
      original: '1 tablespoon toasted sesame seeds',
      originalString: '1 tablespoon toasted sesame seeds',
      originalName: 'toasted sesame seeds',
      metaInformation: [
        'toasted',
      ],
      meta: [
        'toasted',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/sesame-seeds.png',
    },
    {
      id: 2053,
      amount: 2.0,
      unit: 'tablespoons',
      unitLong: 'tablespoons',
      unitShort: 'Tbsp',
      aisle: 'Oil, Vinegar, Salad Dressing',
      name: 'white distilled vinegar',
      original: '2 tablespoons white distilled vinegar',
      originalString: '2 tablespoons white distilled vinegar',
      originalName: 'white distilled vinegar',
      metaInformation: [
        'white',
      ],
      meta: [
        'white',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/vinegar-(white).jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 0,
},
{
  id: 34524,
  title: 'Pickled Bean Sprout Salad',
  image: 'https://spoonacular.com/recipeImages/34524-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11043,
      amount: 6.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Produce',
      name: 'bean sprouts',
      original: 'bean sprouts',
      originalString: 'bean sprouts',
      originalName: 'bean sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
    {
      id: 1022053,
      amount: 6.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Ethnic Foods;Oil, Vinegar, Salad Dressing',
      name: 'rice vinegar',
      original: 'rice vinegar',
      originalString: 'rice vinegar',
      originalName: 'rice vinegar',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/rice-vinegar.png',
    },
    {
      id: 11291,
      amount: 6.0,
      unit: 'servings',
      unitLong: 'servings',
      unitShort: 'servings',
      aisle: 'Produce',
      name: 'scallions',
      original: 'scallions',
      originalString: 'scallions',
      originalName: 'scallions',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 0,
},
{
  id: 564901,
  title: 'Bean Sprouts with Salted Fish',
  image: 'https://spoonacular.com/recipeImages/564901-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 3,
  missedIngredients: [
    {
      id: 11043,
      amount: 200.0,
      unit: 'g',
      unitLong: 'grams',
      unitShort: 'g',
      aisle: 'Produce',
      name: 'bean sprouts',
      original: '200g bean sprouts (heads and tails removed)',
      originalString: '200g bean sprouts (heads and tails removed)',
      originalName: 'bean sprouts (heads and tails removed)',
      metaInformation: [
        '(heads and tails removed)',
      ],
      meta: [
        '(heads and tails removed)',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bean-sprouts.jpg',
    },
    {
      id: 11215,
      amount: 3.0,
      unit: 'cloves',
      unitLong: 'cloves',
      unitShort: 'cloves',
      aisle: 'Produce',
      name: 'garlic',
      original: '3 cloves garlic peeled and minced',
      originalString: '3 cloves garlic peeled and minced',
      originalName: 'garlic peeled and minced',
      metaInformation: [
        'minced',
        'peeled',
      ],
      meta: [
        'minced',
        'peeled',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.jpg',
    },
    {
      id: 14084,
      amount: 1.0,
      unit: 'tbsp',
      unitLong: 'tablespoon',
      unitShort: 'Tbsp',
      aisle: 'Alcoholic Beverages',
      name: 'wine',
      original: '1 tbsp Chinese wine (Hua Tiao/Shao Hsing; optional)',
      originalString: '1 tbsp Chinese wine (Hua Tiao/Shao Hsing; optional)',
      originalName: 'Chinese wine (Hua Tiao/Shao Hsing; optional)',
      metaInformation: [
        'chinese',
        '(Hua Tiao/Shao Hsing; optional)',
      ],
      meta: [
        'chinese',
        '(Hua Tiao/Shao Hsing; optional)',
      ],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/red-wine.jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 0,
},
{
  id: 20573,
  title: 'Farmers Market Green Salad with Fried Shallots',
  image: 'https://spoonacular.com/recipeImages/20573-312x231.jpg',
  imageType: 'jpg',
  usedIngredientCount: 0,
  missedIngredientCount: 4,
  missedIngredients: [
    {
      id: 10011270,
      amount: 6.0,
      unit: 'ounces',
      unitLong: 'ounces',
      unitShort: 'oz',
      aisle: 'Produce',
      name: 'mizuna',
      original: '6 ouncesmizuna and tatsoi (mixed; about 6 cups loosely packed)',
      originalString: '6 ouncesmizuna and tatsoi (mixed; about 6 cups loosely packed)',
      originalName: 'mizuna and tatsoi (mixed; about 6 cups loosely packed)',
      metaInformation: [
        'mixed',
        'loosely packed',
        '(; 6 cups )',
      ],
      meta: [
        'mixed',
        'loosely packed',
        '(; 6 cups )',
      ],
      extendedName: 'mixed mizuna',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/mizuna.jpg',
    },
    {
      id: 11676,
      amount: 0.3333333333333333,
      unit: 'cup',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Produce',
      name: 'radish sprouts',
      original: '1/3 cup radish sprouts',
      originalString: '1/3 cup radish sprouts',
      originalName: 'radish sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
    {
      id: 11677,
      amount: 0.5,
      unit: 'pound',
      unitLong: 'pounds',
      unitShort: 'lb',
      aisle: 'Produce',
      name: 'shallots',
      original: '1/2 pound shallots',
      originalString: '1/2 pound shallots',
      originalName: 'shallots',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/shallots.jpg',
    },
    {
      id: 1002068,
      amount: 1.0,
      unit: 'tablespoon',
      unitLong: 'tablespoon',
      unitShort: 'Tbsp',
      aisle: 'Oil, Vinegar, Salad Dressing',
      name: 'white-wine vinegar',
      original: '1 tablespoon white-wine vinegar',
      originalString: '1 tablespoon white-wine vinegar',
      originalName: 'white-wine vinegar',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/vinegar-(white).jpg',
    },
  ],
  usedIngredients: [],
  unusedIngredients: [
    {
      id: 11001,
      amount: 1.0,
      unit: 'serving',
      unitLong: 'serving',
      unitShort: 'serving',
      aisle: 'Produce',
      name: 'sprouts',
      original: 'sprouts',
      originalString: 'sprouts',
      originalName: 'sprouts',
      metaInformation: [],
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/alfalfa-sprouts.png',
    },
  ],
  likes: 0,
},
];

export default mockFindByIngredient;
